users = User.create([{ nev: "Szabo Peter", email: "szabp@citromail.hu", password: "erospista123" },
                     { nev: "Tamas Eszter", email: "tas@citromail.hu", password: "tami4" },
                     { nev: "Kerek Huba", email: "kerhub@freemail.hu", password: "hubi23" },
                     { nev: "Csoma Taksony", email: "csomag@gmail.com", password: "csoma2" },
                     { nev: "Kalapos Gertrud", email: "kalapge@citromail.hu", password: "akalapos" },
                     { nev: "Lakatos Emanuel", email: "lakatm@citromail.hu", password: "lammelama12" },
                     { nev: "Pecsi Zsofi", email: "pezso@citromail.hu", password: "pezso" },
                     { nev: "geri", email: "geri@gmail.com", password: "admin", admin: true },
                     { nev: "Lakatos Alfonz", email: 'lafikobra@citromail.hu', password: 'hagyma21' },
                     { nev: 'Dombovari Istvan', email: 'veryfunny@citromail.hu', password: 'humoros69' },
                     { nev: 'Puskas Tivadar', email: 'imold@citromail.hu', password: 'jelszo45' },
                     { nev: 'Pepe Frog', email: 'pepe@citromail.hu', password: 'iamameme' },
                     { nev: 'Gorilla Harambe', email: 'HarambethebigG@citromail.hu', password: 'harambe10' },
                     { nev: 'Szep Virag', email: 'flowerpower@citromail.hu', password: 'virag2' },
                     { nev: 'Horthy istvan', email: 'admiralisgeneralis@citromail.hu', password: 'feherlo36' },
                     { nev: 'Adolf Alfonzo', email: 'alfonz@citromail.hu', password: 'alfaalfonz' },
                     { nev: 'Chadwik Chad', email: 'chad@citromail.hu', password: 'cc666' },
                     { nev: 'Mek Elek', email: 'melek@citromail.hu', password: 'melek1' },
                     { nev: 'Kekes Benes', email: 'kbenes@citromail.hu', password: 'kbenes1' },
                     { nev: 'Ritka Rita', email: 'rr@citromail.hu', password: 'rrr1' },
                     { nev: 'Pek Peter', email: 'ppeter@citromail.hu', password: 'ppeter1' },
                     { nev: 'Durcas Tamas', email: 'dtom@citromail.hu', password: 'dtom1' },
                     { nev: 'Beles Bela', email: 'bbela@citromail.hu', password: 'bebal1' },
                     { nev: 'Biro Csaba', email: 'bcs@citromail.hu', password: 'bcs1' },
                     { nev: 'Tubus Bubus', email: 'tb@citromail.hu', password: 'tb1' },
                     { nev: 'Ketrec Harcos', email: 'kfighter@citromail.hu', password: 'fighter69' },
                     { nev: 'Biro Zsoka', email: 'bzs@citromail.hu', password: 'bzs2' },
                     { nev: 'Kincso Mate', email: 'km@citromail.hu', password: 'km2' },
                     { nev: 'Gabor Marton', email: 'gm@citromail.hu', password: 'gm4' },
                     { nev: 'Hajdu Eszter', email: 'he@citromail.hu', password: 'he3' },
                     { nev: 'Horvath David', email: 'hd@citromail.hu', password: 'hd2' },
                     { nev: 'Jozsef Kovacs', email: 'jk@citromail.hu', password: 'jk1' },
                     { nev: 'Katalin Nagy', email: 'kn@citromail.hu', password: 'kn3' },
                     { nev: 'Kiss Balazs', email: 'kb@citromail.hu', password: 'kb7' },
                     { nev: 'Kovari Tamas', email: 'kt@citromail.hu', password: 'kt1' },
                     { nev: 'Laczko Anna', email: 'la@citromail.hu', password: 'la2' },
                     { nev: 'Nagy Zsolt', email: 'nzs@citromail.hu', password: 'nzs3' },
                     { nev: 'Orban Timea', email: 'ot@citromail.hu', password: 'ot1' },
                     { nev: 'Papp Gergely', email: 'pg@citromail.hu', password: 'pg1' },
                     { nev: 'Petrovics Kata', email: 'pk@citromail.hu', password: 'pk1' },
                     { nev: 'Sari Adam', email: 'sa@citromail.hu', password: 'sa1' },
                     { nev: 'Szabo Janos', email: 'szj@citromail.hu', password: 'szj2' },
                     { nev: 'Szekeres Judit', email: 'szja@citromail.hu', password: 'szaj1' },
                     { nev: 'Toth Laszlo', email: 'tl@citromail.hu', password: 'tl' },
                     { nev: 'Varga Zoltan', email: 'vz@citromail.hu', password: 'vz1' },
                     { nev: 'Biro Daniel', email: 'bd@citromail.hu', password: 'budoske1' },
                     { nev: 'Cserhati Erika', email: 'cse@citromail.hu', password: 'csecs2' },
                     { nev: 'Domokos Gabor', email: 'dg@citromail.hu', password: 'dg5' },
                     { nev: 'Farkas Zsuzsa', email: 'fzs@citromail.hu', password: 'fzs3' },
                     { nev: 'Gere Tamas', email: 'gt@citromail.hu', password: 'gt1' },
                     { nev: 'Gyori Viktoria', email: 'gyv@citromail.hu', password: 'gyv2' },
                     { nev: 'Kardos Gabor', email: 'kag@citromail.hu', password: 'kg1' },
                     { nev: 'Bakos Istvan', email: 'bis@citromail.hu', password: 'bi1' },
                     { nev: 'Csanyi Zsolt', email: 'csazs@citromail.hu', password: 'cs1' },
                     { nev: 'David Marta', email: 'dam@citromail.hu', password: 'dam11' },
                     { nev: 'Farkas Laszlo', email: 'fal@citromail.hu', password: 'fal1' },
                     { nev: 'Gyori Kata', email: 'gyok@citromail.hu', password: 'gyok1' },
                     { nev: 'Horvath Bela', email: 'hob@citromail.hu', password: 'hob1' },
                     { nev: 'Juhasz Daniel', email: 'jud@citromail.hu', password: 'jud1' },
                     { nev: 'Karolyi Orsolya', email: 'kor@citromail.hu', password: 'kor1' },
                     { nev: 'Lazar Peter', email: 'lap@citromail.hu', password: 'lap1' },
                     { nev: 'Meszaros Viktoria', email: 'mv@citromail.hu', password: 'mvp1' },
                     { nev: 'Nagy Istvan', email: 'ni@citromail.hu', password: 'ni1' },
                     { nev: 'Orban Lilla', email: 'orl@citromail.hu', password: 'orl1' },
                     { nev: 'Papp Jozsef', email: 'paj@citromail.hu', password: 'paj1' },
                     { nev: 'Sandor Gabor', email: 'sag@citromail.hu', password: 'sag1' },
                     { nev: 'Szabo Anna', email: 'szaa@citromail.hu', password: 'szaa1' },
                     { nev: 'Takacs Gergo', email: 'tag@citromail.hu', password: 'tag1' },
                     { nev: 'Toth Emese', email: 'tem@citromail.hu', password: 'tem1' },
                     { nev: 'Varga Zsuzsanna', email: 'vazs@citromail.hu', password: 'vazs1' },
                     { nev: 'Zsedely Akos', email: 'zsa@citromail.hu', password: 'zsa1' },
                     { nev: 'Zsoter Eszter', email: 'zse@citromail.hu', password: 'zse1' },
                     { nev: 'Balogh Andras', email: 'ba@citromail.hu', password: 'ba1' },
                     { nev: 'Feher Anita', email: 'fa@citromail.hu', password: 'fa1' },
                     { nev: 'Kovacs Gabor', email: 'koga@citromail.hu', password: 'koga1' }])
adverts = Advert.create([{ termek_nev: 'Bolgar Lyukacsos Szikla', mennyiseg: 32000, ar_kg: 180, min_vasarlas: 1000, leiras: 'Kivallo minosegu bolgar lyukacsos szikla elado kedvezo aron ' },
                         { termek_nev: 'Bazalt', mennyiseg: 120000, ar_kg: 990, min_vasarlas: 1000, leiras: 'kiskamospuszati elso osztalyu  haza  fejtettt bazalt 8-10 cm atmeroju' },
                         { termek_nev: 'Gorog hofeher szikla', mennyiseg: 76030, ar_kg: 1501000, min_vasarlas: 1000, leiras: 'Eredeti hellenistica feher szikla a atticai felszigetrol rednkivul olcson ' },
                         { termek_nev: 'Tahiti Uveg Turkiz', mennyiseg: 99995, ar_kg: 1050, min_vasarlas: 1000, leiras: 'Magyarorszagon eloszor a hires tahiti uveg turkiz. premium vagasok excluziv embereknek' },
                         { termek_nev: 'Szivarvanyko', mennyiseg: 62000, ar_kg: 574, min_vasarlas: 1000, leiras: 'Pride, kert , egy csepp szinesseg asziklekrtbe hogy atalgos helyett kiemelkedo  legyen' },
                         { termek_nev: 'Gardenit Extra', mennyiseg: 52020, ar_kg: 2269, min_vasarlas: 1000, leiras: 'Cseh import Gradenit Extra a volt Monarchia egyik leghiresebb banyajabol' },
                         { termek_nev: 'Marvany', mennyiseg: 909856, ar_kg: 2986, min_vasarlas: 1000, leiras: 'Kiraly kis marvany elado prima minoseg meretre vagast illetve fektetest vagy beszerelest vallaok' },
                         { termek_nev: 'Spagetti Koral Szikla', mennyiseg: 351000, ar_kg: 250, min_vasarlas: 1000, leiras: ' sziklakert vagy csak disz ko mi segitunk ilyen olcsomeg soah enm volt sziklakertet epiteni a Spagetti koral sziklankal' },
                         { termek_nev: 'Barnas Meszko', mennyiseg: 32000, ar_kg: 130, min_vasarlas: 1000, leiras: 'Barna meszko a bakony labatol egezsen az udvarig dobja fel unalams kocsi beallojat ezzel a kivallo köfajtaval' },
                         { termek_nev: 'Szorny Szikla', mennyiseg: 89600, ar_kg: 250, min_vasarlas: 1000, leiras: 'ez a ko fajta meg nem trejdt  el kis haznankban de a   nemet alfoldon mar nagyot hoditott ezert elhoztuk neked a hollandok kedvencet a szorny sziklat' },
                         { termek_nev: 'Riolit', mennyiseg: 34000, ar_kg: 1500, min_vasarlas: 1000, leiras: 'egy kalsszikus mindeki ismeri rengeteg eu-s projekthez hazsnaltak es most a te otthonodba is elhozhatja azta z elokeloseget es modernitast amit kepvisel' },
                         { termek_nev: 'Opal', mennyiseg: 34000, ar_kg: 1500, min_vasarlas: 1000, leiras: 'mindeki ismeri a kovek gyongyszeme szo szerint es most egy forinttal se dragabb mint 1500 ft / kg ' },
                         { termek_nev: 'Bezs Meszko Sziklak', mennyiseg: 74000, ar_kg: 55, min_vasarlas: 1000, leiras: 'szep bezsko szikla elado olcsoba' },
                         { termek_nev: 'Meteora Meszko', mennyiseg: 74000, ar_kg: 250, min_vasarlas: 100, leiras: 'Gorogorszag masodik csaoidtol az on hazaig szallitva meteora meszko hogy feldobja az unalmas udvarat' },
                         { termek_nev: 'Sivatagi Rozsa', mennyiseg: 6500, ar_kg: 1900, min_vasarlas: 10, leiras: 'ez a rozsa soha nem szarad el telen is nyaron is ekesiti a sziklakertet' },
                         { termek_nev: 'Fekete Pala', mennyiseg: 84000, ar_kg: 550, min_vasarlas: 1000, leiras: 'gyonoru matt fekete pala kivallo konyhapultnak avgy jarolapnak nagy kemenyseg es gyonyoru latvany' },
                         { termek_nev: 'Granit Golyok', mennyiseg: 90231, ar_kg: 330, min_vasarlas: 1000, leiras: 'ha unod a szabalytalan formakat akkor ezek a golyok neked valok garantaltan feldobjak a koves agyast' },
                         { termek_nev: 'Erezett Marvany', mennyiseg: 21000, ar_kg: 200, min_vasarlas: 1000, leiras: 'a klasszikus elegencia zaloga nem is kell mit mondani rola ugy tokeletes ahogy van ' },
                         { termek_nev: 'Vraca Meszko', mennyiseg: 64000, ar_kg: 250, min_vasarlas: 1000, leiras: 'akar homlokzati burkolas akar padlo eza ko mindent tud nem fogja megbanni ha  ezt valasztja' },
                         { termek_nev: 'Akron', mennyiseg: 64000, ar_kg: 700, min_vasarlas: 1000, leiras: 'klasszikus hegyi lak feeling ki ne ismerni az akront' },
                         { termek_nev: 'Jade', mennyiseg: 64000, ar_kg: 2000, min_vasarlas: 10, leiras: 'Jade ez  gyonoru zold kozet minden kertet feldob' },
                         { termek_nev: 'Travertin', mennyiseg: 44000, ar_kg: 600, min_vasarlas: 1000, leiras: 'szebb es olcsobb is mint a marvany  uygan ugy homlokzatra vagy burkolasra is hazsnalhato kivallo ar/ertek arany' },
                         { termek_nev: 'Brazil Pala', mennyiseg: 54000, ar_kg: 320, min_vasarlas: 1000, leiras: 'a messzi braziliabol importalt pala kozet ' },
                         { termek_nev: 'Indiai Homokko', mennyiseg: 34000, ar_kg: 410, min_vasarlas: 1000, leiras: 'Indiai homokko rendkivuli minoseg kedvezo ar ' },
                         { termek_nev: 'Perlato Meszko', mennyiseg: 22000, ar_kg: 890, min_vasarlas: 1000, leiras: 'Perlato meszko burkoasra homlokzatra burkolas' }])
suppliers = Supplier.create([{ km_ar: 200, ar_kg: 45,ceg_nev:"Kovacs es tarsa Kft." },
                             { km_ar: 210, ar_kg: 37,ceg_nev:"Tamas es tarsa Kft."  },
                             { km_ar: 310, ar_kg: 20,ceg_nev:"Kovek Kft."  },
                             { km_ar: 290, ar_kg: 25,ceg_nev:"Magyarbau Bt."  },
                             { km_ar: 500, ar_kg: 5,ceg_nev:"Tuzep Posta Kft."  },
                             { km_ar: 450, ar_kg: 30,ceg_nev:"Kovek Kft."  },
                             { km_ar: 210, ar_kg: 45,ceg_nev:"szallito Bt."  },
                             { km_ar: 220, ar_kg: 19,ceg_nev:"ko gls Kft."  },
                             { km_ar: 170, ar_kg: 60,ceg_nev:" szikla foxpost "  },
                             { km_ar: 390, ar_kg: 12,ceg_nev:"kavics futar Bt."  },
                             { km_ar: 430, ar_kg: 36,ceg_nev:"Pala palik Kft."  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Stone Giant"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"AranyKapu"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"BacsKeramia"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Cedrus Consult"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Delta-Szolgaltato"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"EdenKert"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Fokusz Media"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"GepMester"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Helioss Kft."  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Infotech Plusz"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Kreativ Idea"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"LapTer Nyomda"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"MagyarVed Kft."  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"NetRing Kft."  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Optimus Consulting"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Penta-Tech"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Quantum System"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Reflektor Studio"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"Sodexo Magyarorszag"  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"TopTrade Kft."  },
                             { km_ar: 330, ar_kg: 30,ceg_nev:"UniCredit Bank Magyarorszag"  }])
carries = Carry.create([{ supplier_id: 1, mit: 'SZIKLA' },
                        { supplier_id: 1, mit: 'BAZALT' },
                        { supplier_id: 2, mit: 'SZIKLA' },
                        { supplier_id: 1, mit: 'UVEG' },
                        { supplier_id: 2, mit: 'SZIVARVANYKO' },
                        { supplier_id: 2, mit: 'GRADENIT' },
                        { supplier_id: 6, mit: 'MARVANY' },
                        { supplier_id: 23, mit: 'SZIKLA' },
                        { supplier_id: 4, mit: 'MESZKO' },
                        { supplier_id: 14, mit: 'SZIKLA' },
                        { supplier_id: 4, mit: 'RIOLIT' },
                        { supplier_id: 15, mit: 'OPAL' },
                        { supplier_id: 5, mit: 'MESZKO' },
                        { supplier_id: 15, mit: 'UVEG' },
                        { supplier_id: 16, mit: 'ROZSA' },
                        { supplier_id: 17, mit: 'PALA' },
                        { supplier_id: 8, mit: 'GRANIT' },
                        { supplier_id: 19, mit: 'MARVANY' },
                        { supplier_id: 10, mit: 'MESZKO' },
                        { supplier_id: 11, mit: 'AKRON' },
                        { supplier_id: 10, mit: 'JADE' },
                        { supplier_id: 19, mit: 'TRAVERTIN' },
                        { supplier_id: 20, mit: 'HOMOKKO' },
                        { supplier_id: 21, mit: 'HOMOKKO' },
                        { supplier_id: 22, mit: 'GRANIT' }])
advertises = Advertise.create([{ user_id: 1, advert_id: 1, mikor: '11-NOV-1999' },
                               { user_id: 1, advert_id: 2, mikor: '11-NOV-1999' },
                               { user_id: 1, advert_id: 3, mikor: '11-JUN-1999' },
                               { user_id: 1, advert_id: 4, mikor: '11-NOV-1999' },
                               { user_id: 1, advert_id: 5, mikor: '12-NOV-1999' },
                               { user_id: 1, advert_id: 6, mikor: '12-JUN-2002' },
                               { user_id: 1, advert_id: 7, mikor: '11-APR-2003' },
                               { user_id: 2, advert_id: 8, mikor: '11-NOV-1999' },
                               { user_id: 3, advert_id: 9, mikor: '11-NOV-1999' },
                               { user_id: 4, advert_id: 10, mikor: '11-JUL-2003' },
                               { user_id: 5, advert_id: 11, mikor: '11-NOV-2007' },
                               { user_id: 5, advert_id: 12, mikor: '01-APR-2005' },
                               { user_id: 5, advert_id: 13, mikor: '11-JUN-2022' },
                               { user_id: 4, advert_id: 14, mikor: '11-NOV-2022' },
                               { user_id: 3, advert_id: 15, mikor: '11-NOV-2022' },
                               { user_id: 2, advert_id: 16, mikor: '03-NOV-2022' },
                               { user_id: 1, advert_id: 17, mikor: '11-APR-2022' },
                               { user_id: 2, advert_id: 18, mikor: '02-NOV-2019' },
                               { user_id: 3, advert_id: 19, mikor: '11-NOV-2019' },
                               { user_id: 3, advert_id: 20, mikor: '08-JUN-2019' },
                               { user_id: 4, advert_id: 21, mikor: '08-JUL-2019' },
                               { user_id: 5, advert_id: 22, mikor: '07-JUL-2019' },
                               { user_id: 6, advert_id: 23, mikor: '09-APR-2019' },
                               { user_id: 5, advert_id: 24, mikor: '06-APR-2019' },
                               { user_id: 5, advert_id: 25, mikor: '09-APR-2019' }])
rates = Rate.create([{ user_id: 6, advert_id: 1, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 6, advert_id: 2, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 13, advert_id: 2, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 11, advert_id: 2, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 7, advert_id: 3, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 7, advert_id: 4, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 7, advert_id: 5, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 8, advert_id: 5, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 8, advert_id: 4, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 9, advert_id: 6, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 10, advert_id: 7, csillag: 5, leiras: 'jo kis cucc mind megjott kivallo minoseg' },
                     { user_id: 11, advert_id: 8, csillag: 3, leiras: 'atlagos' },
                     { user_id: 10, advert_id: 9, csillag: 3, leiras: 'atlagos' },
                     { user_id: 10, advert_id: 10, csillag: 3, leiras: 'atlagos' },
                     { user_id: 13, advert_id: 11, csillag: 3, leiras: 'atlagos' },
                     { user_id: 14, advert_id: 12, csillag: 3, leiras: 'atlagos' },
                     { user_id: 15, advert_id: 13, csillag: 3, leiras: 'atlagos' },
                     { user_id: 6, advert_id: 14, csillag: 3, leiras: 'atlagos' },
                     { user_id: 13, advert_id: 15, csillag: 2, leiras: 'rossz' },
                     { user_id: 14, advert_id: 16, csillag: 2, leiras: 'rossz' },
                     { user_id: 15, advert_id: 17, csillag: 1, leiras: 'rossz' },
                     { user_id: 16, advert_id: 18, csillag: 2, leiras: 'rossz' },
                     { user_id: 11, advert_id: 19, csillag: 4, leiras: 'jo' },
                     { user_id: 7, advert_id: 20, csillag: 4, leiras: 'jo' },
                     { user_id: 7, advert_id: 21, csillag: 4, leiras: 'jo' },
                     { user_id: 9, advert_id: 21, csillag: 4, leiras: 'jo' },
                     { user_id: 9, advert_id: 22, csillag: 4, leiras: 'jo' },
                     { user_id: 9, advert_id: 23, csillag: 4, leiras: 'jo' },
                     { user_id: 7, advert_id: 24, csillag: 4, leiras: 'jo' },
                     { user_id: 6, advert_id: 25, csillag: 4, leiras: 'jo' }])
orders = Order.create([{ user_id: 6, advert_id: 4, supplier_id: 1 },
                       { user_id: 3, advert_id: 4, supplier_id: 1 },
                       { user_id: 3, advert_id: 1, supplier_id: 1 },
                       { user_id: 3, advert_id: 12, supplier_id: 5 },
                       { user_id: 2, advert_id: 23, supplier_id: 7 },
                       { user_id: 2, advert_id: 10, supplier_id: 10 },
                       { user_id: 2, advert_id: 12, supplier_id: 2 },
                       { user_id: 2, advert_id: 13, supplier_id: 2 },
                       { user_id: 6, advert_id: 15, supplier_id: 3 },
                       { user_id: 6, advert_id: 15, supplier_id: 3 },
                       { user_id: 6, advert_id: 15, supplier_id: 4 },
                       { user_id: 6, advert_id: 21, supplier_id: 4 },
                       { user_id: 17, advert_id: 22, supplier_id: 5 },
                       { user_id: 6, advert_id: 23, supplier_id: 5 },
                       { user_id: 6, advert_id: 19, supplier_id: 6 },
                       { user_id: 10, advert_id: 18, supplier_id: 6 },
                       { user_id: 11, advert_id: 17, supplier_id: 7 }])
delivers = Deliver.create([{ order_id: 1, supplier_id: 1, mennyiseg: 1500, hova: 'Kiskerepes Vitez utca 27', koltseg: 1600000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 2, supplier_id: 1, mennyiseg: 2500, hova: 'Fot Petofi koz 13', koltseg: 1600000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 3, supplier_id: 1, mennyiseg: 2500, hova: 'Budapest Galamb utca 10', koltseg: 1650000, varhato_szallitas: '26-MAR-2023' },
                           { order_id: 4, supplier_id: 1, mennyiseg: 1500, hova: 'Budapest Galamb utca 10', koltseg: 1650000, varhato_szallitas: '26-MAR-2023' },
                           { order_id: 5, supplier_id: 1, mennyiseg: 1500, hova: 'Budapest Galamb utca 10', koltseg: 1650000, varhato_szallitas: '26-MAR-2023' },
                           { order_id: 6, supplier_id: 1, mennyiseg: 1500, hova: 'Budapest Galamb utca 10', koltseg: 1665000, varhato_szallitas: '28-MAR-2023' },
                           { order_id: 7, supplier_id: 1, mennyiseg: 3000, hova: 'Budapest Galambutca 10', koltseg: 1780000, varhato_szallitas: '28-MAR-2023' },
                           { order_id: 6, supplier_id: 2, mennyiseg: 1200, hova: 'Budapest Beke 10', koltseg: 280000, varhato_szallitas: '28-MAR-2023' },
                           { order_id: 5, supplier_id: 7, mennyiseg: 1700, hova: 'Budapest Lo 10', koltseg: 1860000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 4, supplier_id: 8, mennyiseg: 1200, hova: 'Budapest Bagira 10', koltseg: 1220000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 6, supplier_id: 2, mennyiseg: 1200, hova: 'Budapest Beke 10', koltseg: 280000, varhato_szallitas: '28-MAR-2023' },
                           { order_id: 5, supplier_id: 7, mennyiseg: 1700, hova: 'Budapest Lo 10', koltseg: 1860000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 4, supplier_id: 8, mennyiseg: 1200, hova: 'Budapest Bagira 10', koltseg: 1220000, varhato_szallitas: '29-MAR-2023' },
                           { order_id: 7, supplier_id: 9, mennyiseg: 1500, hova: 'Kecskemet Beke 10', koltseg: 2100000, varhato_szallitas: '1-APR-2023' },
                           { order_id: 6, supplier_id: 10, mennyiseg: 1700, hova: 'Kecskemet Lo 10', koltseg: 1340000, varhato_szallitas: '1-APR-2023' },
                           { order_id: 5, supplier_id: 10, mennyiseg: 1400, hova: 'Kecskemet Bagira 10', koltseg: 1277000, varhato_szallitas: '1-APR-2023' }])