# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

users = User.create([{nev: "Szabo Peter", email: "szabp@citromail.hu", jelszo: "erospista123"},
                     {nev: "Tamas Eszter", email: "tas@citromail.hu", jelszo: "tami4"},
                     {nev: "Kerek Huba",email: "kerhub@freemail.hu", jelszo: "hubi23"},
                     {nev: "Csoma Taksony", email: "csomag@gmail.com", jelszo: "csoma2"},
                     {nev: "Kalapos Gertrud", email: "kalapge@citromail.hu", jelszo: "akalapos"},
                     {nev: "Lakatos Emanuel", email: "lakatm@citromail.hu", jelszo: "lammelama12"},
                     {nev: "Pecsi Zsofi", email: "pezso@citromail.hu", jelszo: "pezso"},
                     {nev: "Banki Gergely", email: "kicsiq@citromail.hu", jelszo: "password"},
                     {nev: "Lakatos Alfonz", email: 'lafikobra@citromail.hu', jelszo: 'hagyma21'},
                     {nev:'Dombovari Istvan', email:'veryfunny@citromail.hu', jelszo:'humoros69'},
                     {nev:'Puskas Tivadar',email:'imold@citromail.hu',jelszo:'jelszo45'},
                     {nev:'Pepe Frog',email:'pepe@citromail.hu',jelszo:'iamameme'},
                     {nev:'Gorilla Harambe',email:'HarambethebigG@citromail.hu',jelszo:'harambe10'},
                     {nev:'Szep Virag',email:'flowerpower@citromail.hu',jelszo:'virag2'},
                     {nev:'Horthy istvan',email:'admiralisgeneralis@citromail.hu',jelszo:'feherlo36'},
                     {nev:'Adolf Alfonzo',email:'alfonz@citromail.hu',jelszo:'alfaalfonz'},
                     {nev:'Chadwik Chad',email:'chad@citromail.hu',jelszo:'cc666'},
                     {nev:'Biro Zsoka',email:'birozs@citromail.hu',jelszo:'123-45'}])

adverts = Advert.create([{termek_nev:'Bolgar Lyukacsos Szikla',mennyiseg:32000,ar_kg:180,min_vasarlas:1000},
                        {termek_nev:'Bazalt',mennyiseg:120000,ar_kg:990,min_vasarlas:1000},
                        {termek_nev:'Gorog hofeher szikla',mennyiseg:76030,ar_kg:1501000,min_vasarlas:1000},
                         {termek_nev:'Tahiti Uveg Turkiz',mennyiseg:99995,ar_kg:1050,min_vasarlas:1000},
                         {termek_nev:'Szivarvanyko',mennyiseg:62000,ar_kg:574,min_vasarlas:1000},
                         {termek_nev:'Gardenit Extra',mennyiseg:52020,ar_kg:2269,min_vasarlas:1000},
                         {termek_nev:'Marvany',mennyiseg:909856,ar_kg:2986,min_vasarlas:1000},
                         {termek_nev:'Spagetti Koral Szikla',mennyiseg:351000,ar_kg:250,min_vasarlas:1000},
                         {termek_nev:'Barnas Meszko',mennyiseg:32000,ar_kg:130,min_vasarlas:1000},
                         {termek_nev:'Szorny Szikla',mennyiseg:89600,ar_kg:250,min_vasarlas:1000},
                         {termek_nev:'Riolit',mennyiseg:34000,ar_kg:1500,min_vasarlas:1000},
                         {termek_nev:'Opal',mennyiseg:34000,ar_kg:1500,min_vasarlas:1000},
                         {termek_nev:'Bezs Meszko Sziklak',mennyiseg:74000,ar_kg:55,min_vasarlas:1000},
                         {termek_nev:'Meteora Meszko',mennyiseg:74000,ar_kg:250,min_vasarlas:100},
                         {termek_nev:'Sivatagi Rozsa',mennyiseg:6500,ar_kg:1900,min_vasarlas:10},
                         {termek_nev:'Fekete Pala',mennyiseg:84000,ar_kg:550,min_vasarlas:1000},
                         {termek_nev:'Granit Golyok',mennyiseg:90231,ar_kg:330,min_vasarlas:1000},
                         {termek_nev:'Erezett Marvany',mennyiseg:21000,ar_kg:200,min_vasarlas:1000},
                         {termek_nev:'Vraca Meszko',mennyiseg:64000,ar_kg:250,min_vasarlas:1000},
                         {termek_nev:'Akron',mennyiseg:64000,ar_kg:700,min_vasarlas:1000},
                         {termek_nev:'Jade',mennyiseg:64000,ar_kg:2000,min_vasarlas:10},
                         {termek_nev:'Travertin',mennyiseg:44000,ar_kg:600,min_vasarlas:1000},
                         {termek_nev:'Brazil Pala',mennyiseg:54000,ar_kg:320,min_vasarlas:1000},
                         {termek_nev:'Indiai Homokko',mennyiseg:34000,ar_kg:410,min_vasarlas:1000},
                         {termek_nev:'Perlato Meszko',mennyiseg:22000,ar_kg:890,min_vasarlas:1000}])

suppliers = Supplier.create([{km_ar:200,ar_kg:45},
                             {km_ar:210,ar_kg:37},
                             {km_ar:310,ar_kg:20},
                             {km_ar:290,ar_kg:25},
                             {km_ar:500,ar_kg:5},
                             {km_ar:450,ar_kg:30},
                             {km_ar:210,ar_kg:45},
                             {km_ar:220,ar_kg:19},
                             {km_ar:170,ar_kg:60},
                             {km_ar:390,ar_kg:12},
                             {km_ar:430,ar_kg:36},
                             {km_ar:330,ar_kg:30}])

carries = Carry.create([{supplier_id:1,mit:'Lyukacsos Szikla'},
                        {supplier_id:1,mit:'Bazalt'},
                        {supplier_id:1,mit:'Gorog Hofeher Szikla'},
                        {supplier_id:1,mit:'Tahiti uveg Turkiz'},
                        {supplier_id:2,mit:'Szivarvanyko'},
                        {supplier_id:2,mit:'Gardenit Extra'},
                        {supplier_id:6,mit:'Marvany'},
                        {supplier_id:3,mit:'Spagettikoral Szikla'},
                        {supplier_id:4,mit:'Barnas Meszko'},
                        {supplier_id:4,mit:'Szorny Szikla'},
                        {supplier_id:4,mit:'Riolit'},
                        {supplier_id:5,mit:'Opal'},
                        {supplier_id:5,mit:'Bezs Meszko'},
                        {supplier_id:5,mit:'Meteora Meszko'},
                        {supplier_id:6,mit:'Sivatagi Rozsa'},
                        {supplier_id:7,mit:'Fekete Pala'},
                        {supplier_id:8,mit:'Granit Golyok'},
                        {supplier_id:9,mit:'Erezett Marvany'},
                        {supplier_id:10,mit:'Vraca Meszko'},
                        {supplier_id:11,mit:'Akron'},
                        {supplier_id:10,mit:'Jade'},
                        {supplier_id:9,mit:'Travertin'},
                        {supplier_id:7,mit:'Brazil Pala'},
                        {supplier_id:6,mit:'Indiai Homokko'},
                        {supplier_id:5,mit:'Perlato Meszko'}])

advertises = Advertise.create([{user_id:1,advert_id:1,mikor:'11-NOV-1999'},
                               {user_id:1,advert_id:2,mikor:'11-NOV-1999'},
                               {user_id:1,advert_id:3,mikor:'11-JUN-1999'},
                               {user_id:1,advert_id:4,mikor:'11-NOV-1999'},
                               {user_id:1,advert_id:5,mikor:'12-NOV-1999'},
                               {user_id:1,advert_id:6,mikor:'12-JUN-2002'},
                               {user_id:1,advert_id:7,mikor:'11-APR-2003'},
                               {user_id:2,advert_id:8,mikor:'11-NOV-1999'},
                               {user_id:3,advert_id:9,mikor:'11-NOV-1999'},
                               {user_id:4,advert_id:10,mikor:'11-JUL-2003'},
                               {user_id:5,advert_id:11,mikor:'11-NOV-2007'},
                               {user_id:5,advert_id:12,mikor:'01-APR-2005'},
                               {user_id:5,advert_id:13,mikor:'11-JUN-2022'},
                               {user_id:4,advert_id:14,mikor:'11-NOV-2022'},
                               {user_id:3,advert_id:15,mikor:'11-NOV-2022'},
                               {user_id:2,advert_id:16,mikor:'03-NOV-2022'},
                               {user_id:1,advert_id:17,mikor:'11-APR-2022'},
                               {user_id:2,advert_id:18,mikor:'02-NOV-2019'},
                               {user_id:3,advert_id:19,mikor:'11-NOV-2019'},
                               {user_id:3,advert_id:20,mikor:'08-JUN-2019'},
                               {user_id:4,advert_id:21,mikor:'08-JUL-2019'},
                               {user_id:5,advert_id:22,mikor:'07-JUL-2019'},
                               {user_id:6,advert_id:23,mikor:'09-APR-2019'},
                               {user_id:5,advert_id:24,mikor:'06-APR-2019'},
                               {user_id:5,advert_id:25,mikor:'09-APR-2019'}])

rates = Rate.create([{user_id:6,advert_id:1,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:6,advert_id:2,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:13,advert_id:2,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:11,advert_id:2,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:7,advert_id:3,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:7,advert_id:4,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:7,advert_id:5,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:8,advert_id:5,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:8,advert_id:4,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:9,advert_id:6,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:10,advert_id:7,csillag:5,leiras:'jo kis cucc mind megjott kivallo minoseg'},
                     {user_id:11,advert_id:8,csillag:3,leiras:'atlagos'},
                     {user_id:10,advert_id:9,csillag:3,leiras:'atlagos'},
                     {user_id:10,advert_id:10,csillag:3,leiras:'atlagos'},
                     {user_id:13,advert_id:11,csillag:3,leiras:'atlagos'},
                     {user_id:14,advert_id:12,csillag:3,leiras:'atlagos'},
                     {user_id:15,advert_id:13,csillag:3,leiras:'atlagos'},
                     {user_id:6,advert_id:14,csillag:3,leiras:'atlagos'},
                     {user_id:13,advert_id:15,csillag:2,leiras:'rossz'},
                     {user_id:14,advert_id:16,csillag:2,leiras:'rossz'},
                     {user_id:15,advert_id:17,csillag:1,leiras:'rossz'},
                     {user_id:16,advert_id:18,csillag:2,leiras:'rossz'},
                     {user_id:11,advert_id:19,csillag:4,leiras:'jo'},
                     {user_id:7,advert_id:20,csillag:4,leiras:'jo'},
                     {user_id:7,advert_id:21,csillag:4,leiras:'jo'},
                     {user_id:9,advert_id:21,csillag:4,leiras:'jo'},
                     {user_id:9,advert_id:22,csillag:4,leiras:'jo'},
                     {user_id:9,advert_id:23,csillag:4,leiras:'jo'},
                     {user_id:7,advert_id:24,csillag:4,leiras:'jo'},
                     {user_id:6,advert_id:25,csillag:4,leiras:'jo'}])

orders = Order.create([{user_id:6,advert_id:4,supplier_id:1},
                       {user_id:3,advert_id:4,supplier_id:1},
                       {user_id:13,advert_id:1,supplier_id:1},
                       {user_id:13,advert_id:12,supplier_id:5},
                       {user_id:13,advert_id:23,supplier_id:7},
                       {user_id:13,advert_id:21,supplier_id:10},
                       {user_id:13,advert_id:20,supplier_id:11}])

delivers = Deliver.create([{order_id:1,supplier_id:1,mennyiseg:1500,hova:'Kiskerepes Vitez utca 27',koltseg:1600000,varhato_szallitas:'29-MAR-2023'},
                           {order_id:2,supplier_id:1,mennyiseg:2500,hova:'Fot Petofi koz 13',koltseg:1600000,varhato_szallitas:'29-MAR-2023'},
                           {order_id:3,supplier_id:1,mennyiseg:2500,hova:'Budapest Galamb utca 10',koltseg:1650000,varhato_szallitas:'26-MAR-2023'},
                           {order_id:4,supplier_id:1,mennyiseg:1500,hova:'Budapest Galamb utca 10',koltseg:1650000,varhato_szallitas:'26-MAR-2023'},
                           {order_id:5,supplier_id:1,mennyiseg:1500,hova:'Budapest Galamb utca 10',koltseg:1650000,varhato_szallitas:'26-MAR-2023'},
                           {order_id:6,supplier_id:1,mennyiseg:1500,hova:'Budapest Galamb utca 10',koltseg:1665000,varhato_szallitas:'28-MAR-2023'},
                           {order_id:7,supplier_id:1,mennyiseg:1500,hova:'Budapest Galambutca 10',koltseg:1780000,varhato_szallitas:'28-MAR-2023'}])